export const SEARCH_PARKING = 'SEARCH_PARKING';
export const SEARCH_PARKING_NO_RESULTS = 'SEARCH_PARKING_NO_RESULTS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_PAGE_LOADING = 'CHANGE_PAGE_LOADING';